name: Setup

runs:
  using: composite
  steps:
    - name: Install tools
      uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
    - name: Install dependencies
      shell: bash
      run: pnpm install
