name: Setup

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: '.tool-versions'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install
