export const siteMetaData = {
  title: "Nissy's Blog",
  author: "Daiki Nishikawa",
  nickname: "Nissy",
  headerTitle: "Nissy's Blog",
  description: "A blog for Nissy",
  language: "en-us",
  siteUrl: "",
  siteRepo: "https://github.com/nissy-dev/blog",
  siteLogo: "/static/images/logo.png",
  image: "/static/images/avatar.png",
  socialBanner: "/static/images/twitter-card.png",
  email: "nd.12021218@gmail.com",
  github: "https://github.com/nissy-dev",
  twitter: "https://twitter.com/nissy_dev",
};
