name: auto merge for renovate

on:
  pull_request:
    branches:
      - main

  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      github.event.pull_request.user.login == 'renovate[bot]' && \
      contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: "blog"
      - run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
