name: base workflow
on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - name: Check action pins
        run: pinact run --check --verify-comment .github/workflows/*.yaml .github/actions/setup/action.yaml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run lint
        run: pnpm run lint
      - name: Run typecheck
        run: pnpm run typecheck
