name: contents update workflow
on:
  push:
    branches:
      - main
    paths:
      - 'contents/**'
      - '.github/workflows/contents.yaml'
  workflow_dispatch:

jobs:
  db-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Deploy new worker
        working-directory: packages/fts
        run: pnpm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Update database
        working-directory: packages/fts
        run: |
          pnpm run db:prod:reset -- --yes
          pnpm run db:prod:init -- --yes
          pnpm run db:prod:insert
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          AUTH_INFO: ${{ secrets.AUTH_INFO }}
