name: Update index
on: [deployment_status]
jobs:
  update-index:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: update index
        run: |
          CONFIG=$(cat docsearch.json | jq -r tostring)
          pipenv run python -m src.index
        env:
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
