name: Update index
on:
  deployment_status:
    branches:
      - main
jobs:
  update-index:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: algolia/docsearch-scraper
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare environment variable
        run: |
          apt-get update -y && apt -y install jq
          echo "CONFIG=$(cat docsearch.json | jq -r tostring)" >> $GITHUB_ENV
      # see: https://github.com/adapttive/algolia-docsearch-action
      - name: update index
        run: |
          cd /root && pipenv install && pipenv run python -m src.index
        env:
          WORKON_HOME: /root
          PIPENV_PIPFILE: /root/Pipfile
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          CONFIG: ${{ env.CONFIG }}
