name: Update index
on: [deployment_status]
jobs:
  update-index:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: update index
        uses: algolia/docsearch-scraper
        run: |
          ls
          apt-get update -y && apt -y install jq
          CONFIG=$(cat docsearch.json | jq -r tostring)
          pipenv run python -m src.index
        env:
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
