name: Renovate

on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: "blog"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@630a255a1f2f56c8d8ce160bed3e3ca577ca53e2 # v40.2.7
        with:
          configurationFile: renovate.json5
          token: ${{ steps.get_token.outputs.token }}
        env:
          LOG_LEVEL: "debug"
